version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: realsoccer_mongodb
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: realsoccer_db
    restart: always

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: realsoccer_server
    ports:
      - "${SERVER_PORT}:5001"
    environment:
      NODE_ENV: ${NODE_ENV}
      MONGO_URI: mongodb://${MONGO_ROOT_USERNAME}:${MONGO_ROOT_PASSWORD}@mongodb:27017/realsoccer_db?authSource=admin
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN}
      # Add other server-specific environment variables here
    depends_on:
      - mongodb
    volumes:
      - ./server:/app
      - /app/node_modules # Prevent host node_modules from overwriting container's
    restart: always

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: realsoccer_client
    ports:
      - "${CLIENT_PORT}:3000"
    environment:
      NODE_ENV: ${NODE_ENV}
      REACT_APP_API_URL: http://server:5000/api # Corrected from localhost
    volumes:
      - ./client:/app
      - /app/node_modules # Prevent host node_modules from overwriting container's
    depends_on:
      - server
    restart: always

volumes:
  mongodb_data: